# Generated by Django 2.2.6 on 2019-12-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('title', models.CharField(max_length=100)),
                ('post_text', models.TextField()),
            ],
        ),
    ]
